apiVersion: v1
kind: ConfigMap
metadata:
  name: blue-content
data:
  index.html: |
    <html><body style="background:#3498db;color:white;text-align:center;">
    <h1>BLUE VERSION - v1.0</h1></body></html>